FROM python:3.11-slim

WORKDIR /app_kafka

RUN apt-get update && apt-get install -y \
    openjdk-21-jdk \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY consumer.py /app_kafka/

RUN pip install pyspark==3.5.0

CMD ["spark-submit", "--packages","org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0","consumer.py"]